# This file was generated by EventLoop GridDriver for EL job prwSubmit22
t = AtlasTask()
t.name = 'prwSubmit22'
t.float = 200
config.Athena.EXE_MAXFILESIZE=2097152
print
print "TaskID: %d" % t.id
print "TaskContainer: %s" % t.getContainerName()

# Transform 1
trf = AtlasTransform()
trf.name = 'mc12_8TeV.208001.Pythia8B_AU2_CTEQ6L1_pp_Jpsimu4mu4.merge.NTUP_SMWZ.e1331_a159_a173_r3549_p1067'
t.appendTransform(trf)
trf.initializeFromContainer('mc12_8TeV.208001.Pythia8B_AU2_CTEQ6L1_pp_Jpsimu4mu4.merge.NTUP_SMWZ.e1331_a159_a173_r3549_p1067/')
for u in trf.units: u.inputdata.names_pattern = ['*.root*']
trf.inputsandbox = ['/nfs/scratch0/jblanco/CalibrationWork/RunPileupPRW/prwSubmit22/elg/inputsandbox/jobdef.root','/nfs/scratch0/jblanco/CalibrationWork/RunPileupPRW/prwSubmit22/elg/inputsandbox/runjob.sh']
trf.application = Athena()
trf.application.option_file = 'runjob.sh'
trf.application.options = 'mc12_8TeV.208001.Pythia8B_AU2_CTEQ6L1_pp_Jpsimu4mu4.merge.NTUP_SMWZ.e1331_a159_a173_r3549_p1067'
trf.application.atlas_exetype = 'EXE'
trf.application.useRootCore = True
trf.application.append_to_user_area = ['.root','.cxx','.C','.h']
trf.application.prepare()
trf.outputdata = DQ2OutputDataset()
trf.outputdata.datasetname = 'user.jayb88.mc12_8TeV.208001.Pythia8B_AU2_CTEQ6L1_pp_Jpsimu4mu4.merge.NTUP_SMWZ.e1331_a159_a173_r3549_p1067'
trf.outputdata.outputdata = ['hist-output.root','output.root','outFile.root']
trf.backend = Panda()
trf.local_location = '/nfs/scratch0/jblanco/CalibrationWork/RunPileupPRW/prwSubmit22/elg/download/mc12_8TeV.208001.Pythia8B_AU2_CTEQ6L1_pp_Jpsimu4mu4.merge.NTUP_SMWZ.e1331_a159_a173_r3549_p1067'
trf.include_file_mask = ['hist-output.root']
trf.MB_per_job = 13000
trf.backend.requirements.excluded_sites = ['ANALY_IN2P3-CC-T2']

t.run()
import time
time.sleep(60)
